application: application_name
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: web/favicon\.ico
  expiration: "14d"

env_variables:
  SLACK_TOKEN: 'slack token'
